package Classes.Pieces;

import Classes.Board;
import Classes.Game;
import Classes.Location;
import Classes.Move;
import Utility.Enums;

import java.util.ArrayList;

/**
 * Class for King piece
*/
public class King extends Piece {

    public boolean hasMoved; // For castling

    /**
     * Constructs a new king piece
     * @param color of the piece
     * @param location the piece spawns in
     */
    public King(Enums.Color color, Location location) {
        super(color, location);
        hasMoved = false;
    }

    public King(String pieceDatum, String pieceDatum1, String pieceDatum2, String pieceDatum3) {
        super(pieceDatum, pieceDatum1, pieceDatum2);
        hasMoved = pieceDatum3.equals("1");
    }

    /**
     * Gets all possible moves for king piece
     * @param game reference to the game
     * @return moves ArrayList of all valid moves for piece
     */
    @Override
    public ArrayList<Move> getMoves(Game game) {
        Board board = game.getBoard();

        ArrayList<Move> moves = new ArrayList<Move>();

        // check all adjacent locations (don't worry about moving onto itself because of other checks in place)
        for (int i = -1; i <= 1; i++) {
            for (int j = -1; j <= 1; j++) {
                if (canMove(this.location,j,i,board)) {
                    moves.add(new Move(this.location,new Location(this.location.colIndex()+j,this.location.rowIndex()+i)));
                }
            }
        }

        //check if can castle
        int row = (getColor() == Enums.Color.White ? 0 : 7);
        boolean clearPathToLeftRook = board.pieceAt(1,row)==null && board.pieceAt(2,row)==null && board.pieceAt(3,row)==null;
        if (!hasMoved && clearPathToLeftRook && board.pieceAt(0,row)!=null && board.pieceAt(0,row).getClass()==Rook.class) {
            Rook leftRook = (Rook) board.pieceAt(0, row);
            if (!leftRook.getHasMoved()) {
                moves.add(new Move("O-O-O"));
            }
        }
        boolean clearPathToRightRook = board.pieceAt(5,row)==null && board.pieceAt(6,row)==null;
        if (!hasMoved && clearPathToRightRook && board.pieceAt(7,row)!=null && board.pieceAt(7,row).getClass()==Rook.class) {
            Rook rightRook = (Rook) board.pieceAt(7, row);
            if (!rightRook.getHasMoved()) {
                moves.add(new Move("O-O"));
            }
        }

        return moves;
    }

    /**
     * Sets king's location, and declares it has moved
     *
     * @param location  New desired location for pawn
     */
    @Override
    public void move(Location location) {
        this.location = location;
        hasMoved = true;
        System.out.println("KING MOVED");   //TESTING
    }

    /**
     * sets has moved to false, used in Undos
     */
    public void undoCastle() {
        hasMoved = false;
    }

    /**
     * Represents piece as string, for displaying on board
     *
     * @return King piece represented as string. Ex) wK for white king
     */
    @Override
    public String toString() {
        return (color.equals(Enums.Color.White)?"w":"b") + "K";
    }

    public boolean isInCheck(Game game){
        // get 5x5 square around king
        // check possible moves of all enemy pieces in that square
        // if any of those include where the king is, then the king's in check, return true
        Location kingLocation = this.getLocation();
        for (int i = -7; i <= 7; i++) { // column
            for (int j = -7; j <= 7; j++) { // row
                Piece scanPiece = game.getBoard().pieceAt(kingLocation.colIndex()+i, kingLocation.rowIndex()+j);
                if(scanPiece != null){
                    if(!scanPiece.getColor().equals(this.getColor())){
                        ArrayList<Move> moves = scanPiece.getMoves(game);
                        for(int k = 0; k < moves.size(); ++k){
                            Move move = moves.get(k);
                            if(move.getTo()!=null && move.getTo().toString().equals(kingLocation.toString())){
                                return true;
                            }
                        }
                    }
                }
            }
        }

        // then, do the same for diagonals and straights (use march?)


        return false; // else, if we get to the end and no check, false
    }

    /**
     * special get data function for this piece to include the hasMoved boolean
     * @return  the data string generated by the piece
     */
    @Override
    public String getData() {
        StringBuilder returnString = new StringBuilder(super.getData());
        returnString.append(" ");
        returnString.append(hasMoved?"1":"0");

        return returnString.toString();
    }
}
